# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-05-23 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='context',
        ),
        migrations.AddField(
            model_name='room',
            name='context',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
