# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-05-23 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20170523_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='context',
            field=models.TextField(default={}),
        ),
    ]
